---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(rvest)
```


```{r}
data("rest_inspec")

rest_inspec=
  rest_inspec |> 
  slice(1:1000) |> 
   filter(grade %in% c("A", "B", "C", "D"), boro != "Missing") 

```


Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
rest_inspec |> 
   filter(cuisine_description %in% c("American", "Korean", "Café/Coffee/Tea", "Pizza", "Irish", "Italian")) |> 
  mutate(cuisine_description = fct_reorder(cuisine_description, score, .fun = median)) |> 
  plot_ly(
    x = ~cuisine_description,
    y = ~score,
    type = "box"
  ) |>
  layout(
    title = "Average Inspection Score by Most Common Cuisines",
    xaxis = list(title = "Cuisine", tickangle = 45),
    yaxis = list(title = "Inspection Score")
  )
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
rest_inspec |> 
  filter(cuisine_description %in% c("American", "Korean", "Café/Coffee/Tea", "Pizza", "Irish", "Italian")) |>
  count(cuisine_description) |> 
  mutate(cuisine_description=fct_reorder(cuisine_description, n)) |> 
  plot_ly(
    x = ~cuisine_description, y = ~n, color = ~cuisine_description, type = "bar"
  ) |> 
  layout(
    title = "Count of Most Common Cuisine Descriptions",
    xaxis = list(title = "Cuisine Description"),
    yaxis = list(title = "Count")
  )
```

### Chart C

```{r}
rest_inspec |> 
   filter(cuisine_description %in% c("American", "Korean", "Café/Coffee/Tea", "Pizza", "Irish", "Italian")) |> 
  mutate(year = year(inspection_date)) |> 
  count(year, cuisine_description) |> 
  plot_ly(
    x = ~year,
    y = ~n,
    color = ~cuisine_description,
    type = "scatter",
    mode = "lines",
    text = ~paste("Cuisine:", cuisine_description, "<br>Year:", year, "<br>Violations:", n)
  ) |>
  layout(
    title = "Violations by Year and Most Common Cuisine",
    xaxis = list(title = "Year"),
    yaxis = list(title = "Violation Count"),
    legend = list(title = list(text = "Cuisine"))
  )

```

